[theme]
base = "light"
primaryColor = "#0077b5"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333F"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
# Force light theme
toolbarMode = "minimal"
showSidebarNavigation = true
theme = "light"